class Country < ActiveHash::Base
  self.data = [
    { id: 1,  region: '--',     name: '--' },
    { id: 2,  region: 'Africa', name: 'Algeria' },
    { id: 3,  region: 'Africa', name: 'Angola' },
    { id: 4, region: 'South America', name: 'Argentina' },
    { id: 5, region: 'Oceania', name: 'Australia' },
    { id: 6, region: 'Middle East', name: 'Bahrain' },
    { id: 7, region: 'South America', name: 'Bolivia' },
    { id: 8, region: 'South America', name: 'Brazil' },
    { id: 9, region: 'North America', name: 'Canada' },
    { id: 10, region: 'South America', name: 'Chile' },
    { id: 11, region: 'Asia', name: 'China' },
    { id: 12, region: 'South America', name: 'Columbia' },
    { id: 13, region: 'Central America', name: 'Costa Rica' },
    { id: 14, region: 'Central America', name: 'Cuba' },
    { id: 15, region: 'South America', name: 'Ecuador' },
    { id: 16,  region: 'Africa', name: 'Egypt' },
    { id: 17, region: 'Central America', name: 'El Salvador' },
    { id: 18,  region: 'Africa', name: 'Ethiopia' },
    { id: 19, region: 'Europe', name: 'France' },
    { id: 20, region: 'Europe', name: 'Germany' },
    { id: 21,  region: 'Africa', name: 'Ghana' },
    { id: 22, region: 'Central America', name: 'Guatemala' },
    { id: 23, region: 'Central America', name: 'Haiti' },
    { id: 24, region: 'Central America', name: 'Honduras' },
    { id: 25, region: 'Asia', name: 'Hong Kong' },
    { id: 26, region: 'Asia', name: 'India' },
    { id: 27, region: 'Asia', name: 'Indonesia' },
    { id: 28, region: 'Middle East', name: 'Iran' },
    { id: 29, region: 'Middle East', name: 'Israel' },
    { id: 30, region: 'Europe', name: 'Italy' },
    { id: 31, region: 'Central America', name: 'Jamaica' },
    { id: 32, region: 'Asia', name: 'Japan' },
    { id: 33,  region: 'Africa', name: 'Kenya' },
    { id: 34, region: 'Asia', name: 'Korea' },
    { id: 35, region: 'Asia', name: 'Malaysia' },
    { id: 36, region: 'North America', name: 'Mexico' },
    { id: 37,  region: 'Africa', name: 'Morocco' },
    { id: 38, region: 'Europe', name: 'Netherland' },
    { id: 39, region: 'Oceania', name: 'New Zealand' },
    { id: 40,  region: 'Africa', name: 'Nigeria' },
    { id: 41, region: 'Central America', name: 'Panama' },
    { id: 42, region: 'South America', name: 'Paraguay' },
    { id: 43, region: 'South America', name: 'Peru' },
    { id: 44, region: 'Europe', name: 'Portugal' },
    { id: 45, region: 'Middle East', name: 'Qatar' },
    { id: 46, region: 'Europe', name: 'Russia' },
    { id: 47, region: 'Middle East', name: 'Saudi Arabia' },
    { id: 48, region: 'Asia', name: 'Singapore' },
    { id: 49, region: 'Africa', name: 'South Africa' },
    { id: 50, region: 'Europe', name: 'Spain' },
    { id: 51, region: 'Europe', name: 'Sweden' },
    { id: 52, region: 'Europe', name: 'Switzerland' },
    { id: 53, region: 'Asia', name: 'Taiwan' },
    { id: 54, region: 'Africa', name: 'Tanzania' },
    { id: 55, region: 'Asia', name: 'Thailand' },
    { id: 56, region: 'Middle East', name: 'Turkey' },
    { id: 57, region: 'Middle East', name: 'UAE' },
    { id: 58, region: 'Europe', name: 'United Kingdom' },
    { id: 59, region: 'North America', name: 'United States of America' },
    { id: 60, region: 'South America', name: 'Uruguay' },
    { id: 61, region: 'South America', name: 'Venezuela' },
    { id: 62, region: 'Middle East', name: 'Yamen' },
  ]  
end
